osm_data:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 'osm_data_db'
      port: 5432
      dbname: "{{ env_var('TARGET_DB_NAME') }}"
      user: "{{ env_var('TARGET_DB_USER') }}"
      password: "{{ env_var('TARGET_DB_PASSWORD') }}"
      schema: 'dbt'