services:
  # This service runs the postgres DB used by dagster for run storage, schedule storage,
  # and event log storage.
  dagster_db:
    image: postgres
    container_name: dagster_db
    restart: always
    env_file:
      - dagster/dagster_db_credentials.env
    networks:
      - osm_data_pet_project_network

  # This service runs single instance dagster container.
  dagster:
    build:
      context: .
      dockerfile: dagster/Dockerfile
    container_name: dagster
    restart: always
    env_file:
      - dagster/dagster_db_credentials.env
    ports:
      - "3000:3000"
    volumes:
      - ./dagster/repo.py:/opt/dagster/app/repo.py
    networks:
      - osm_data_pet_project_network
    depends_on:
      - dagster_db

networks:
  osm_data_pet_project_network:
    driver: bridge
    name: osm_data_pet_project_network